#!/bin/bash
# TinyShell Phase 3 - Comprehensive Testing Script
# Run this to verify all job control features

echo "=========================================="
echo "TinyShell Phase 3 - Testing Checklist"
echo "=========================================="
echo ""

echo "Prerequisites:"
echo "1. Compile with: make clean && make"
echo "2. Run tinyshell: ./tinyshell"
echo ""
echo "Then follow these manual tests:"
echo ""

echo "==================== TEST 1: Background Jobs Don't Receive Ctrl-C ===================="
echo "Commands:"
echo "  tinyshell> sleep 100 &"
echo "  [1] XXXX"
echo "  tinyshell> # Press Ctrl-C here"
echo "  tinyshell> jobs"
echo ""
echo "Expected: Job [1] should still be Running (not terminated by Ctrl-C)"
echo "Status: [ ] PASS  [ ] FAIL"
echo ""

echo "==================== TEST 2: Foreground Jobs Do Receive Ctrl-C ===================="
echo "Commands:"
echo "  tinyshell> sleep 100"
echo "  ^C[terminated by signal: Interrupt]"
echo "  tinyshell>"
echo ""
echo "Expected: sleep should terminate immediately, shell returns to prompt"
echo "Status: [ ] PASS  [ ] FAIL"
echo ""

echo "==================== TEST 3: Ctrl-Z Stops Foreground Jobs ===================="
echo "Commands:"
echo "  tinyshell> sleep 100"
echo "  ^Z"
echo "  [1]+ Stopped    sleep 100"
echo "  tinyshell> jobs"
echo "  [1]  Stopped    sleep 100"
echo ""
echo "Expected: Job should be stopped and added to job list"
echo "Status: [ ] PASS  [ ] FAIL"
echo ""

echo "==================== TEST 4: fg Brings Job to Foreground ===================="
echo "Commands:"
echo "  tinyshell> sleep 100"
echo "  ^Z"
echo "  [1]+ Stopped    sleep 100"
echo "  tinyshell> fg %1"
echo "  sleep 100"
echo "  ^C"
echo "  tinyshell>"
echo ""
echo "Expected: Job resumes in foreground, can be terminated with Ctrl-C"
echo "Status: [ ] PASS  [ ] FAIL"
echo ""

echo "==================== TEST 5: bg Resumes Job in Background ===================="
echo "Commands:"
echo "  tinyshell> sleep 100"
echo "  ^Z"
echo "  [1]+ Stopped    sleep 100"
echo "  tinyshell> bg %1"
echo "  [1]+ sleep 100 &"
echo "  tinyshell> jobs"
echo "  [1]  Running    sleep 100"
echo ""
echo "Expected: Job continues running in background"
echo "Status: [ ] PASS  [ ] FAIL"
echo ""

echo "==================== TEST 6: Shell Regains Terminal After Job Exits ===================="
echo "Commands:"
echo "  tinyshell> sleep 2"
echo "  # Wait 2 seconds"
echo "  [exit status: 0]"
echo "  tinyshell> # Prompt returns automatically"
echo ""
echo "Expected: Shell prompt returns after job completes"
echo "Status: [ ] PASS  [ ] FAIL"
echo ""

echo "==================== TEST 7: Multiple Background Jobs Work Correctly ===================="
echo "Commands:"
echo "  tinyshell> sleep 100 &"
echo "  [1] XXXX"
echo "  tinyshell> sleep 200 &"
echo "  [2] XXXX"
echo "  tinyshell> sleep 300 &"
echo "  [3] XXXX"
echo "  tinyshell> jobs"
echo "  [1]  Running    sleep 100"
echo "  [2]  Running    sleep 200"
echo "  [3]  Running    sleep 300"
echo ""
echo "Expected: All three jobs tracked correctly"
echo "Status: [ ] PASS  [ ] FAIL"
echo ""

echo "==================== TEST 8: Zombies Are Properly Reaped ===================="
echo "Commands:"
echo "  tinyshell> sleep 3 &"
echo "  [1] XXXX"
echo "  # In another terminal: ps aux | grep sleep"
echo "  # Wait 4 seconds"
echo "  # Check again: ps aux | grep sleep"
echo ""
echo "Expected: No <defunct> processes after sleep completes"
echo "Also check notification:"
echo "  tinyshell> ls  # or any command"
echo "  [1]+ Done       sleep 3"
echo ""
echo "Status: [ ] PASS  [ ] FAIL"
echo ""

echo "==================== TEST 9: Pipeline Job Control ===================="
echo "Commands:"
echo "  tinyshell> cat | grep test"
echo "  ^Z"
echo "  [1]+ Stopped    cat | grep"
echo "  tinyshell> fg %1"
echo "  cat | grep"
echo "  ^C"
echo "  [terminated by signal: Interrupt]"
echo ""
echo "Expected: Pipeline can be stopped and resumed"
echo "Status: [ ] PASS  [ ] FAIL"
echo ""

echo "==================== TEST 10: Error Handling ===================="
echo "Commands:"
echo "  tinyshell> fg %99"
echo "  fg: %99: no such job"
echo "  tinyshell> bg %1  # when job 1 is running"
echo "  bg: job %1 already running"
echo ""
echo "Expected: Proper error messages"
echo "Status: [ ] PASS  [ ] FAIL"
echo ""

echo "=========================================="
echo "Advanced Debugging Commands (if needed)"
echo "=========================================="
echo ""
echo "1. Check process groups:"
echo "   ps j"
echo ""
echo "2. List all signals:"
echo "   kill -l"
echo ""
echo "3. Trace signal operations:"
echo "   strace -e signal ./tinyshell"
echo ""
echo "4. Find all sleep processes:"
echo "   pgrep -a sleep"
echo ""
echo "5. Check process state:"
echo "   cat /proc/[pid]/stat"
echo ""
echo "6. Monitor job changes:"
echo "   watch -n 1 'ps j | grep tinyshell'"
echo ""

echo "=========================================="
echo "Summary Checklist"
echo "=========================================="
echo "[ ] Background jobs don't receive Ctrl-C"
echo "[ ] Foreground jobs do receive Ctrl-C"
echo "[ ] Ctrl-Z stops foreground jobs"
echo "[ ] fg brings job to foreground"
echo "[ ] bg resumes job in background"
echo "[ ] Shell regains terminal after job exits"
echo "[ ] Multiple background jobs work correctly"
echo "[ ] Zombies are properly reaped"
echo "[ ] Pipelines handle signals correctly"
echo "[ ] Error messages are clear"
echo ""
echo "If all tests pass: ✅ Phase 3 COMPLETE!"
echo "=========================================="
